foreground         #c2c3c6
background         #171717
background_opacity 1.0
cursor             #c2c3c6

active_tab_foreground     #1e1d1d
active_tab_background     #c2c3c6
inactive_tab_foreground   #c2c3c6
inactive_tab_background   #1e1d1d

active_border_color   #c2c3c6
inactive_border_color #0c121b
bell_border_color     #1e374b

cursor_beam_thickness 0.25
cursor_underline_thickness 0.25

shell zsh


color0       #ffffff
color8       #5b626f
color1       #1e374b
color9       #284A65
color2       #3d3645
color10      #52495C
color3       #092369
color11      #0C2F8C
color4       #0f4b6c
color12      #146491
color5       #3c3982
color13      #504DAE
color6       #6e4a75
color14      #93639C
color7       #8f9399
color15      #c2c3c6
